with ctms_stg__subject_summary_by_visit as 
(
select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("enroll or screen fail date" as varchar) as "enroll or screen fail date"
,Null as "protocol version randomized"
,cast("cohort" as varchar) as "cohort"
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,cast("eotxb date" as varchar) as "eotxb date"
,Null as "nivolumab eot date"
,Null as "ipilimumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,cast("death date" as varchar) as "death date"
,cast("eorfup date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xb002-101_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xb002-101_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xb002-101_subject_summary_by_visit') }})

union all


select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,CASE WHEN 
length(cast("subject number" as varchar)) = 4 THEN 
'000000'||'-'||cast(left(site, 4) AS varchar)||'-'||cast("subject number" as varchar) 
else '000000'||cast("subject number" as varchar)
end as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date subject  first signed  informed consent" as varchar) as "date of first icf"
,cast("enrollment or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol  version" as varchar) as "protocol version randomized"
,cohort as "cohort"
,cast("treatment  description" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,cast("xl092 first dose date" as varchar) as "eotxb date"
,Null as "nivolumab eot date"
,Null as "sunitinib eot date"
,"atezo eot date"
,Null as "ipilimumab eot date"
,cast("death date" as varchar) as "death date"
,cast("eorfup date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit short name" as varchar) as "visit short name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,Null as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,Null as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,Null as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,Null as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,Null as "% missing >90 days"
,cast("incomplete pgs" as varchar) as "entered pgs"
,Null as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,Null as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,Null as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,Null as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,Null as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,Null as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,Null as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,Null as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,Null as "<30 days after report date"
,Null as "31-60 days after report date"
,Null as "61-90 days after report date"
,Null as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xl092-001_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl092-001_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl092-001_subject_summary_by_visit') }})

union all


select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("enrolled randomized or screen fail date date" as varchar) as "enroll or screen fail date"
,cast("protocol version" as varchar) as "protocol version randomized"
,Null as "cohort"
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,cast("xl092  eot date" as varchar) as "eotxb date"
,"nivolumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,"ipilimumab eot date"
,cast("death date" as varchar) as "death date"
,cast("erfu date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xl092-002_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl092-002_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl092-002_subject_summary_by_visit') }})

union all

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("randomization or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version randomized" as varchar) as "protocol version randomized"
,Null as "cohort"
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,cast("xl092  eot date" as varchar) as "eotxb date"
,Null as "nivolumab eot date"
,"atezolizumab eot date" as "atezo eot date"
,Null as "sunitinib eot date"
,Null as "ipilimumab eot date"
,cast("death date" as varchar) as "death date"
,cast("erfu date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xl092-303_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl092-303_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl092-303_subject_summary_by_visit') }})

union all

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("enroll or screen fail date" as varchar) as "enroll or screen fail date"
,Null as "protocol version randomized"
,cast("cohort" as varchar) as "cohort"
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,Null as "nivolumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,Null as "ipilimumab eot date"
,cast("eotx date" as varchar) as "eotxb date"
,cast("death date" as varchar) as "death date"
,cast("eorfup date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xl102-101_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl102-101_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl102-101_subject_summary_by_visit') }})
/*

union all

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("rand or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version randomized" as varchar) as "protocol version randomized"
,Null as "cohort"
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,Null as "nivolumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,Null as "ipilimumab eot date"
,cast("eotc date" as varchar) as "eotxb date"
,cast("death date" as varchar) as "death date"
,cast("eorfup date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xl184-315_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl184-315_subject_summary_by_visit') }})
*/

union all

select
case 
    when upper(country)='UNITED STATES OF AMERICA' then  'UNITED STATES'
    when upper(country)='CZECHIA' then  'CZECH REPUBLIC'
    else upper(country)
end AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("rand or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version randomized" as varchar) as "protocol version randomized"
,null as "cohort"
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,"nivolumab eot date" as "nivolumab eot date"
,Null as "atezo eot date"
,"sunitinib eot date" as "sunitinib eot date"
,Null as "ipilimumab eot date"
,Null as "eotxb date"
,cast("death date" as varchar) as "death date"
,cast("erfu date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("91-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xl092-304_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl092-304_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl092-304_subject_summary_by_visit') }})


union all

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,case when "site"='2124 - Richard Zuniga' then '1841 - Richard Zuniga'
else cast("site" as varchar) 
end as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("randomization or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version randomized" as varchar) as "protocol version randomized"
,cast(cohort as varchar ) as "cohort"
,null as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,"nivolumab eot date" as "nivolumab eot date"
,Null as "atezo eot date"
,null as "sunitinib eot date"
,Null as "ipilimumab eot date"
,cast("xl092  eot date" as varchar) as "eotxb date"
,cast("death date" as varchar) as "death date"
,Null as "eorfup date"
,case 
	when "esfu reason" in ('Death') then "esfu date"
	else null 
end as "eos date"
,case 
	when "esfu reason" in ('Death') then "esfu reason" 
	else NULL
end as "eos reason"
,cast("esfu date" as varchar) as "esfu date"
,cast("esfu reason" as varchar) as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from 
    {{ source ('koios_raw', 'xl092-009_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl092-009_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl092-009_subject_summary_by_visit') }})

union all

select
 REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
 ,cast("site" as varchar)  as "site"
 ,cast("subject number" as varchar) as "subject number"
 ,cast("subject status" as varchar) as "subject status"
 ,cast("date of first icf" as varchar) as "date of first icf"
 ,null as "enroll or screen fail date"
 ,cast("protocol version randomized" as varchar) as "protocol version randomized"
 ,null as "cohort"
 ,null as "treatment arm"
 ,cast("most recent visit" as varchar) as "most recent visit"
 ,cast("most recent date of visit" as varchar) as "most recent date of visit"
 ,"nivolumab eot date" as "nivolumab eot date"
 ,Null as "atezo eot date"
 ,null as "sunitinib eot date"
 ,Null as "ipilimumab eot date"
 ,cast("xl092  eot date" as varchar) as "eotxb date"
 ,cast("death date" as varchar) as "death date"
 ,Null as "eorfup date"
 ,null as "eos date"
 ,null as "eos reason"
 ,null as "esfu date"
 ,null as "esfu reason"
 ,cast("visit name" as varchar) as "visit name"
 ,cast("total expected pgs" as varchar) as "total expected pgs"
 ,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
 ,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
 ,cast("missing <30 days" as varchar) as "missing <30 days"
 ,cast("% missing <30 days" as varchar) as "% missing <30 days"
 ,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
 ,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
 ,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
 ,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
 ,cast("missing >90 days" as varchar) as "missing >90 days"
 ,cast("% missing >90 days" as varchar) as "% missing >90 days"
 ,cast("entered pgs" as varchar) as "entered pgs"
 ,cast("% entered pgs" as varchar) as "% entered pgs"
 ,cast("sv not started" as varchar) as "sv not started"
 ,cast("% sv not started" as varchar) as "% sv not started"
 ,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
 ,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
 ,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
 ,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
 ,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
 ,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
 ,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
 ,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
 ,cast("sv incomplete" as varchar) as "sv incomplete"
 ,cast("% sv incomplete" as varchar) as "% sv incomplete"
 ,cast("sv complete" as varchar) as "sv complete"
 ,cast("% sv complete" as varchar) as "% sv complete"
 ,cast("open" as varchar) as "open"
 ,cast("open <30 days" as varchar) as "open <30 days"
 ,cast("open 31-60 days" as varchar) as "open 31-60 days"
 ,cast("open 61-90 days" as varchar) as "open 61-90 days"
 ,cast("open >90 days" as varchar) as "open >90 days"
 ,cast("answered pending review" as varchar) as "answered pending review"
 ,cast("<30 days after report date" as varchar) as "<30 days after report date"
 ,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
 ,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
 ,null as "90-180 days after report date"
 ,cast("studyid" as varchar) as "studyid"
 ,partition_date as load_date
from 
    {{ source ('koios_raw', 'xl092-305_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl092-305_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl092-305_subject_summary_by_visit') }})

union all

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,CASE WHEN 
length(cast("subject number" as varchar)) = 4 THEN 
'000000'||'-'||cast(left(site, 4) AS varchar)||'-'||cast("subject number" as varchar) 
else '000000'||cast("subject number" as varchar)
end as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("randomization or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version randomized" as varchar) as "protocol version randomized"
,Null as "cohort"
,null as "treatment arm"
,null as "most recent visit"
,null as "most recent date of visit"
,Null as "nivolumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,Null as "ipilimumab eot date"
,cast("eot date (blinded)" as varchar) as "eotxb date"
,null as "death date"
,null as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit short name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,null as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,null as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,null as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,null as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,null as "% missing >90 days"
,cast("completed pgs" as varchar) as "entered pgs"
,null as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,null as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,null as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,null as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,null as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,null as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,null as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,null as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("open <30 days" as varchar) as "<30 days after report date"
,cast("open 31-60 days" as varchar) as "31-60 days after report date"
,cast("open 61-90 days" as varchar) as "61-90 days after report date"
,cast("open >90 days" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
{{ source ('koios_raw', 'xl184_311_subject_summary_by_visit') }}
where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl184_311_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl184_311_subject_summary_by_visit') }})

union all 

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,CASE WHEN 
length(cast("subject number" as varchar)) = 4 THEN 
'000000'||'-'||cast(left(site, 4) AS varchar)||'-'||cast("subject number" as varchar) 
else '000000'||cast("subject number" as varchar)
end as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("rand or screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version randomized" as varchar) as "protocol version randomized"
,Null as "cohort"
,null as "treatment arm"
,null as "most recent visit"
,null as "most recent date of visit"
,Null as "nivolumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,Null as "ipilimumab eot date"
,cast("eot date (cabo)" as varchar) as "eotxb date"
,null as "death date"
,null as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,null as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit short name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,null as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,null as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,null as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,null as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,null as "% missing >90 days"
,cast("completed pgs" as varchar) as "entered pgs"
,null as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,null as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,null as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,null as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,null as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,null as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,null as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,null as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("open <30 days" as varchar) as "<30 days after report date"
,cast("open 31-60 days" as varchar) as "31-60 days after report date"
,cast("open 61-90 days" as varchar) as "61-90 days after report date"
,cast("open >90 days" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
{{ source ('koios_raw', 'xl184-312_subject_summary_by_visit') }}
where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xl184-312_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xl184-312_subject_summary_by_visit') }})

union all

select
REPLACE(upper(country), 'UNITED STATES OF AMERICA', 'UNITED STATES') AS country
,cast("site" as varchar) as "site"
,cast("subject number" as varchar) as "subject number"
,cast("subject status" as varchar) as "subject status"
,cast("date of first icf" as varchar) as "date of first icf"
,cast("enrolled/randomized/ screen fail date" as varchar) as "enroll or screen fail date"
,cast("protocol version" as varchar) as "protocol version randomized"
,case 
    when split_part(cohort,':',1) like 'COHORT A1%' then 'Cohort A1'
    when split_part(cohort,':',1) like 'COHORT A2%' then 'Cohort A2'
    else initcap(split_part(cohort,':',1))
end as cohort
,cast("treatment arm" as varchar) as "treatment arm"
,cast("most recent visit" as varchar) as "most recent visit"
,cast("most recent date of visit" as varchar) as "most recent date of visit"
,null as "eotxb date"
,Null as "nivolumab eot date"
,Null as "ipilimumab eot date"
,Null as "atezo eot date"
,Null as "sunitinib eot date"
,cast("death date" as varchar) as "death date"
,cast("erfu date" as varchar) as "eorfup date"
,cast("eos date" as varchar) as "eos date"
,cast("eos reason" as varchar) as "eos reason"
,null as "esfu date"
,null as "esfu reason"
,cast("visit name" as varchar) as "visit name"
,cast("total expected pgs" as varchar) as "total expected pgs"
,cast("missing pgs (entry not started)" as varchar) as "missing pgs (entry not started)"
,cast("% missing pgs (entry not started)" as varchar) as "% missing pgs (entry not started)"
,cast("missing <30 days" as varchar) as "missing <30 days"
,cast("% missing <30 days" as varchar) as "% missing <30 days"
,cast("missing 31-60 days" as varchar) as "missing 31-60 days"
,cast("% missing 31-60 days" as varchar) as "% missing 31-60 days"
,cast("missing 61-90 days" as varchar) as "missing 61-90 days"
,cast("% missing 61-90 days" as varchar) as "% missing 61-90 days"
,cast("missing >90 days" as varchar) as "missing >90 days"
,cast("% missing >90 days" as varchar) as "% missing >90 days"
,cast("entered pgs" as varchar) as "entered pgs"
,cast("% entered pgs" as varchar) as "% entered pgs"
,cast("sv not started" as varchar) as "sv not started"
,cast("% sv not started" as varchar) as "% sv not started"
,cast("sv not started <30 days" as varchar) as "sv not started <30 days"
,cast("% sv not started <30 days" as varchar) as "% sv not started <30 days"
,cast("sv not started 31-60 days" as varchar) as "sv not started 31-60 days"
,cast("% sv not started 31-60 days" as varchar) as "% sv not started 31-60 days"
,cast("sv not started 61-90 days" as varchar) as "sv not started 61-90 days"
,cast("% sv not started 61-90 days" as varchar) as "% sv not started 61-90 days"
,cast("sv not started >90 days" as varchar) as "sv not started >90 days"
,cast("% sv not started >90 days" as varchar) as "% sv not started >90 days"
,cast("sv incomplete" as varchar) as "sv incomplete"
,cast("% sv incomplete" as varchar) as "% sv incomplete"
,cast("sv complete" as varchar) as "sv complete"
,cast("% sv complete" as varchar) as "% sv complete"
,cast("open" as varchar) as "open"
,cast("open <30 days" as varchar) as "open <30 days"
,cast("open 31-60 days" as varchar) as "open 31-60 days"
,cast("open 61-90 days" as varchar) as "open 61-90 days"
,cast("open >90 days" as varchar) as "open >90 days"
,cast("answered pending review" as varchar) as "answered pending review"
,cast("<30 days after report date" as varchar) as "<30 days after report date"
,cast("31-60 days after report date" as varchar) as "31-60 days after report date"
,cast("61-90 days after report date" as varchar) as "61-90 days after report date"
,cast("90-180 days after report date" as varchar) as "90-180 days after report date"
,cast("studyid" as varchar) as "studyid"
,partition_date as load_date
from
    {{ source ('koios_raw', 'xb010-101_subject_summary_by_visit') }}
    where last_modified_date = (select max(last_modified_date) from {{ source ('koios_raw', 'xb010-101_subject_summary_by_visit') }})
    and partition_date = (select max(partition_date) from {{ source ('koios_raw', 'xb010-101_subject_summary_by_visit') }})

)

select * from ctms_stg__subject_summary_by_visit
