from pathlib import Path

from conftest import REPO_ROOT, import_module_from_path


# These tests exercise the notification framework utilities without needing a live
# Databricks cluster. The goal is to validate SQL escaping, recipient selection,
# and email formatting in a deterministic, unit-level way.


def _notification_dir():
    # Centralize the path to the notification framework so tests can import modules
    # from the same folder as the application code.
    return REPO_ROOT / r"databricks_bundle\drugdev\notification_faramework"


def test_sql_str_escapes_quotes_truncates_and_handles_none(stub_pyspark):
    # sql_str is used for safe interpolation into SQL strings. These checks confirm
    # we preserve the contract: None becomes empty string, embedded quotes are doubled
    # for SQL compatibility, and long inputs are trimmed when a max length is supplied.
    sql_utils = import_module_from_path(
        "notification_sql_utils",
        r"databricks_bundle\drugdev\notification_faramework\sql_utils.py",
    )

    assert sql_utils.sql_str(None) == ""
    assert sql_utils.sql_str("O'Brien") == "O''Brien"
    assert sql_utils.sql_str("abcdef", max_len=3) == "abc"


def test_sql_identifier_allows_expected_names_and_rejects_injection(stub_pyspark):
    # SQL identifiers are stricter than raw string values. We allow naming patterns
    # that are common in schemas and tables, but reject characters or sequences that
    # can be used to break SQL or carry malicious input into a query.
    sql_utils = import_module_from_path(
        "notification_sql_utils_identifiers",
        r"databricks_bundle\drugdev\notification_faramework\sql_utils.py",
    )

    # A normal dotted identifier name should pass unchanged.
    assert sql_utils.sql_identifier("catalog.schema.table-name") == "catalog.schema.table-name"

    # Anything that looks like injection or malformed identifier syntax should raise
    # a ValueError with context information in the message.
    for unsafe in ["", "table;DROP TABLE x", "schema/table", "name\nother"]:
        try:
            sql_utils.sql_identifier(unsafe, context="unit")
        except ValueError as exc:
            assert "unit" in str(exc)
        else:
            raise AssertionError(f"Expected {unsafe!r} to be rejected")


def test_clean_where_clause_escapes_values_and_validates_extra_columns(stub_pyspark):
    # clean_where_clause should produce a safe SQL WHERE fragment. It must handle
    # default use cases and ensure any data values are escaped before being inserted.
    sql_utils = import_module_from_path(
        "notification_sql_utils_where",
        r"databricks_bundle\drugdev\notification_faramework\sql_utils.py",
    )

    # Empty input should still yield a harmless condition that does not filter rows.
    assert sql_utils.clean_where_clause() == "1=1"

    # When values include quotes or extra filter columns, the method should preserve
    # the intended semantics while keeping the query safe and valid.
    assert sql_utils.clean_where_clause(
        domain="EDC",
        vendor="O'Brien",
        extra={"study_id": "XL092-303"},
    ) == "domain = 'EDC' AND vendor = 'O''Brien' AND study_id = 'XL092-303'"


def test_alert_notifier_resolves_domain_recipients_before_defaults(stub_pyspark):
    # AlertNotifier is expected to prefer domain-specific routing over the generic
    # default recipients. This protects teams that need different notification lists
    # based on domain, while still providing fallback behavior for unknown domains.
    notifier_mod = import_module_from_path(
        "notification_alert_notifier",
        r"databricks_bundle\drugdev\notification_faramework\alert_notifier.py",
        extra_sys_path=[_notification_dir()],
    )
    notifier = notifier_mod.AlertNotifier(
        {
            "notifications": {
                "email": {"recipients": {"high": ["default@example.com"]}},
                "domain_recipients": {"EDC": {"email": ["edc@example.com"]}},
            }
        }
    )

    # For a known domain, we should use the domain-specific address instead of the
    # generic default recipient.
    assert notifier._resolve_recipients("HIGH", "edc") == ["edc@example.com"]

    # For an unknown domain, the fallback default should be used.
    assert notifier._resolve_recipients("HIGH", "unknown") == ["default@example.com"]


def test_alert_email_body_contains_severity_color_and_context(stub_pyspark):
    # This verifies the HTML body generated by AlertNotifier contains the expected
    # severity styling and the alert details that help operators quickly diagnose the
    # issue when email notifications are received.
    notifier_mod = import_module_from_path(
        "notification_alert_notifier_body",
        r"databricks_bundle\drugdev\notification_faramework\alert_notifier.py",
        extra_sys_path=[_notification_dir()],
    )
    notifier = notifier_mod.AlertNotifier({})

    body = notifier._format_email_body("Pipeline failed", "Bad records found", {"rows": 3}, "HIGH")

    # Severity color is used to make the alert visually stand out in the email.
    assert "color:#f57c00" in body

    # The message should include the severity prefix and title in the subject line.
    assert "[HIGH] Pipeline failed" in body

    # Context values should be rendered into the email table in a readable form.
    assert "<td><b>rows</b></td><td>3</td>" in body
